#!/usr/bin/ansible-playbook --inventory=inventory
- name: vars overlay
  hosts: localhost
  gather_facts: true
  vars_files:
  - vars/vault.yml
  - vars/bastion.yml
  - vars/cluster.yml
  - vars/fabric.yml

  tasks:
    - name: '{{ ansible_name_module }} | import_tasks | Import variable overlay tasks'
      ansible.builtin.include_tasks: tasks/repo-overlay.yml
      when:
        - run_overlay_var is defined
        - run_overlay_var | bool

- name: "Konductor | Provision UPI Infra | config-local-aws-terraform-provider.yml"
  hosts: localhost
  vars_files:
  - vars/vault.yml
  - vars/bastion.yml
  - vars/cluster.yml
  - vars/fabric.yml
  vars:
    module: "configure-aws-terraform-provider-local"
  tasks:
    - name: '{{ ansible_name_module }} | install aws terraform provider'
      when:
        - install_terraform_provider is defined
        - install_terraform_provider | bool
      block:
        - name: '{{ ansible_name_module }} | shell | get installed tf version '
          shell: terraform version | head -n 1 | awk '{print $2}'
          ignore_errors: true
          register: ter_ver 

        - name: '{{ ansible_name_module }} | file:state=directory | Ensure terraform provider directory exist '
          file:
            path: "{{ terraform_provider_dir }}"
            state: directory
            recurse: true

        - name: '{{ ansible_name_module }} | file:state=directory | for each provider '
          file:
            path: "{{ terraform_provider_dir }}/{{ terraform_domain }}/{{ terraform_namespace }}/{{ install_terraform_provider_name }}/{{ install_terraform_provider_version }}/{{ terraform_provider_type }}"
            state: directory
            recurse: true

        - name: '{{ ansible_name_module }} | unarchive | bundle provider files to host'
          unarchive:
            src: "{{ install_terraform_provider_binary }}"
            remote_src: yes
            dest: "{{ terraform_provider_dir }}/{{ terraform_domain }}/{{ terraform_namespace }}/{{ install_terraform_provider_name }}/{{ install_terraform_provider_version }}/{{ terraform_provider_type }}"
            mode: 0755
          register: unbundle_out

    - name: '{{ ansible_name_module }} | Configure aws terraform provider'
      when:
        - (install_terraform_provider is defined and install_terraform_provider | bool) or (config_terraform_provider is defined and config_terraform_provider | bool)
      block:
        - name: '{{ ansible_name_module }} | template | create terraform provider v14 config file'
          template:
            src: "templates/terraformrc-aws.j2"
            dest: "{{ terraform_provider_dir }}/main.tf"
            mode: 0755
            force: yes

        #- name: '{{ ansible_name_module }} | template | create terraform provider v14 config file'
        #  template:
        #    src: "templates/provider-local.j2"
        #    dest: "{{ terraform_provider_dir }}/provider.tf"
        #    mode: 0755
        #    force: yes

        #- name: '{{ ansible_name_module }} | shell:terraform.init | Initilize terraform provider module'
        #  shell: >
        #    cd {{ terraform_provider_dir }} && terraform init && terraform plan
        #  failed_when:
        #    - terraform_init.rc > 1
        #    - " not 'not available for installation' in terraform_init.stderr "
        #  register: terraform_init

        - name: '{{ ansible_name_module }} | shell:terraform.init | Initilize terraform provider module'
          shell:
            cmd: terraform init 
            chdir: "{{ terraform_provider_dir }}"
          failed_when:
            - terraform_init.rc > 1
            - " not 'not available for installation' in terraform_init.stderr "
          register: terraform_init

