---
- name: vars overlay
  hosts: localhost
  gather_facts: true
  vars:
    git_repo_branch: ''
    stage_dir: ''
    separate_git_dir: "{{ stage_dir }}/repo"
    project_dir: "{{ stage_dir }}/project"
    cluster_dir: ''
    git_repo: ''
    #Leave blank if executing locally, otherwises use saved credential from AAP Controller
    ssh_private_key_file: "{{ lookup('env', 'SSH_GIT_PRIVATE_KEY') | default(omit) }}"

  tasks:
    - name: '{{ ansible_name_module }} | import_tasks | Import variable overlay tasks'
      ansible.builtin.import_tasks: tasks/repo-overlay.yml

- hosts: local,localhost
  
  vars_files:
  - vars/vault.yml
  - vars/bastion.yml
  - vars/environment.yml
  - vars/cluster.yml
  - vars/fabric.yml

  tasks:
    - name: Make sure unzip is installed
      yum:
        name: unzip
        state: present
      become: 'true'

    - name: Download binaries
      get_url:
        url: "https://{{ binary_location }}/{{ item }}"
        dest: "/tmp/{{ item }}"
        username: "{{ vault_registry_admin_username }}"
        password: "{{ vault_registry_admin_password }}"
        force_basic_auth: 'true'
      with_items:
        - "{{ oc_client_binary }}"
        - "{{ oc_installer_binary }}"
        - "{{ terraform_binary }}"
        - "{{ terraform_provider_binary }}"

    - name: Unpack oc binaries
      unarchive:
        src: "/tmp/{{ item }}"
        dest: /usr/bin/
      with_items:
        - "{{ oc_client_binary }}"
        - "{{ oc_installer_binary }}"
      become: 'true'

    - name: Unpack terraform
      command: unzip -o "/tmp/{{ terraform_binary }}" -d /usr/local/bin/
      become: 'true'

    - name: '{{ ansible_name_module }} | command:which | Check if openshift-install-fips is installed'
      ansible.builtin.shell: >
        which openshift-install-fips 
      ignore_errors: yes
      register: oc_install_fips_binary_check

    - name: '{{ ansible_name_module }} | command:shell | set symlink if openshift-install-fips is installed'
      ansible.builtin.shell: >
        ln -s -f {{ oc_install_fips_binary_check.stdout }} {{ oc_install_fips_binary_check.stdout.split('-fips')[0] }} 
      when:
        - oc_install_fips_binary_check is defined
        - oc_install_fips_binary_check.rc is defined
        - oc_install_fips_binary_check.rc == 0 
        - oc_install_fips_binary_check.stdout is defined
        - oc_install_fips_binary_check.stdout != '' 
      become: 'true'

