#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: vars overlay
  hosts: localhost
  gather_facts: true
  vars:
    ansible_name_module: " vars overlay"
    stage_dir: /tmp/platform
    separate_git_dir: "{{ stage_dir }}/repo"
    project_dir: "{{ stage_dir }}/project"
    cluster_dir: ''
    git_repo: '' 
    #Leave blank if executing locally, otherwises use saved credential from AAP Controller
    ssh_private_key_file: "{{ lookup('env', 'SSH_GIT_PRIVATE_KEY') | default(omit) }}"

  tasks:
    - name: '{{ ansible_name_module }} | import_tasks | Import variable overlay tasks'
      ansible.builtin.import_tasks: tasks/repo-overlay.yml

- hosts: registry,local,localhost
  become: true
  vars_files:
  - vars/vault.yml
  - vars/common.yml
  - vars/ansible-collections.yml
  vars:
    module: "setup-bastion"
    ansible_name_module: " Pre Cluster Installation | {{ module }}"
  pre_tasks:
     - name: '{{ ansible_name_module }} | Ensure required variables are set'
       block:
         - ansible.builtin.assert:
             that:
               - hub_url is defined and hub_url != ""
             msg: " the private hub url must be set and valid "
         - ansible.builtin.assert:
             that:
               -  hub_token is defined and hub_token != ""
             msg: " the private hub hub_token must be set and valid "
         - ansible.builtin.assert:
             that:
               - galaxy_repos is defined and galaxy_repos != "" and galaxy_repos | length > 0
             msg: " the galaxy_repos must be set and valid list of repos to pull collections from"

  tasks:
    - name: Render ansible galaxy section of the ansible.cfg file 
      ansible.builtin.template:
        src: "templates/galaxy.cfg.j2"
        dest: "{{ staging_dir }}/ansible.cfg"
        force: true

    - name: Copy Rendered galaxy config into place if applicable 
      ansible.builtin.copy:
        src: "{{ staging_dir }}/ansible.cfg"
        dest: "{{ ansible_cfg_dir | default('/etc/ansible', true) }}/ansible.cfg"
        owner: root
        group: root
        mode: '0655'
        force: true

    - name: Copy platform to platform_staging_dir 
      when:
        - install_collections is defined
        - install_collections | bool
      block: 
        - name: '{{ ansible_name_module }} | command:which | Check if ansible-galaxy is installed'
          ansible.builtin.shell: >
            which ansible-galaxy
          ignore_errors: yes
          register: ansible_galaxy_binary_check

        - name: '{{ ansible_name_module }} | assert | ansible-galaxy is installed'
          ansible.builtin.assert:
            that:
              - ansible_galaxy_binary_check is defined
              - ansible_galaxy_binary_check.rc is defined
              - ansible_galaxy_binary_check.rc == 0
              - ansible_galaxy_binary_check.stdout is defined
              - ansible_galaxy_binary_check.stdout != ''
            msg: "The ansible-galaxy package is required before running this"

        - name: '{{ ansible_name_module }} | set_fact | ansible_galaxy_binary'
          ansible.builtin.set_fact:
            ansible_galaxy_binary: "{{ ansible_galaxy_binary_check.stdout }}"

        - name: Install collections 
          ansible.builtin.shell: >
           {{ ansible_galaxy_binary }} collection install {{ item }} --force 
          loop: "{{ ansible_collections }}"
          when:
            - ansible_collections is defined 
            - ansible_collections | d([],true) | length > 0
            - not collection_requirements_file is defined or collection_requirements_file == '' 

        - name: Install collections using provided requirement.yml 
          ansible.builtin.shell: >
           {{ ansible_galaxy_binary }} collection install -r {{ collection_requirements_file }} --force 
          when:
            - collection_requirements_file is defined
            - collection_requirements_file != '' 
            - not ansible_collections is defined or ansible_collections | d([],true) | length == 0 or ansible_collections == ''
