#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: vars overlay
  hosts: localhost
  gather_facts: true
  vars:
    stage_dir: /tmp/platform
    separate_git_dir: "{{ stage_dir }}/repo"
    project_dir: "{{ stage_dir }}/project"
    cluster_dir: ''
    git_repo: ''
    #Leave blank if executing locally, otherwises use saved credential from AAP Controller
    ssh_private_key_file: "{{ lookup('env', 'SSH_GIT_PRIVATE_KEY') | default(omit) }}"

  tasks:
    - name: '{{ ansible_name_module }} | import_tasks | Import variable overlay tasks'
      ansible.builtin.include_tasks: tasks/repo-overlay.yml

