#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'run-nginx-container.yml' 
  hosts: localhost 
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    module: "Run Nginx Container for Webserver in case there is no web server"
    ansible_name_module: "{{ module }}"
  vars_files:
          #- 'vars/vault.yml'
    - 'vars/environment.yml'

  pre_tasks:
    - name: '{{ ansible_name_module }} | Ensure required variables are set'
      block:
        - assert:
            that:
              - nginx_container_image is defined and nginx_container_image != ""
            msg: " the nginx_container_image must be set "
          when:
            - not load_container_image is defined or not load_container_image | bool or not container_image_archive_file is defined or  container_image_archive_file == '' 

        - assert:
            that:
              - nginx_container_cert is defined and nginx_container_cert != ""
            msg: " the nginx_container_cert must be set "

        - assert:
            that:
              - nginx_container_key is defined and nginx_container_key != ""
            msg: " the nginx_container_key must be set "

        - assert:
            that:
              - nginx_webserver_dir is defined and nginx_webserver_dir != ""
            msg: " the nginx_webserver_dir must be set "

        - name: '{{ ansible_name_module }} | stat | Check if nginx_container_cert file exist'
          ansible.builtin.stat:
            path: "{{ nginx_container_cert }}"
            get_checksum: false
          register: certfile_exist

        - assert:
            that:
              - certfile_exist.stat is defined
              - certfile_exist.stat.exists is defined
              - certfile_exist.stat.exists | bool 
              - certfile_exist.stat.path is defined
              - certfile_exist.stat.path != '' 
            msg: " the nginx_container_cert must be a valid pem formatted cert on the controller"

        - name: '{{ ansible_name_module }} | stat | Check if nginx_container_key file exist'
          ansible.builtin.stat:
            path: "{{ nginx_container_key }}"
            get_checksum: false
          register: certkeyfile_exist

        - assert:
            that:
              - certkeyfile_exist.stat is defined
              - certkeyfile_exist.stat.exists is defined
              - certkeyfile_exist.stat.exists | bool 
              - certkeyfile_exist.stat.path is defined
              - certkeyfile_exist.stat.path != '' 
            msg: " the nginx_container_key must be a valid pem formatted key on the controller"

    - name: '{{ ansible_name_module }} | ansible.builtin.command:which | Check if podman is installed'
      block:
        - name: '{{ ansible_name_module }} | ansible.builtin.command:which | Check if oc-mirror is installed'
          ansible.builtin.shell: >
            which podman
          ignore_errors: yes
          register: podman_binary

        - name: '{{ ansible_name_module }} | set_fact |  podman_cli'
          ansible.builtin.set_fact:
            podman_cli: "{{ podman_binary.stdout }}"
          when:
            - podman_binary is defined
            - podman_binary.rc is defined
            - podman_binary.rc == 0
            - podman_binary.stdout is defined
            - podman_binary.stdout != ''
  tasks:
    - name: '{{ ansible_name_module }} | Load Registry image from archive'
      when:
        - load_container_image is defined
        - load_container_image | bool
        - container_image_archive_file is defined 
        - container_image_archive_file != '' 
      block:
        - name: '{{ ansible_name_module }} | stat | Check if nginx_container_image file exist'
          ansible.builtin.stat:
            path: "{{ nginx_container_image }}"
            get_checksum: false
          register: nginx_container_image_exist

        - name: '{{ ansible_name_module }} | command:podman:load | load'
          command: podman load -i {{ container_image_archive_file }}
          when:
            - nginx_container_image_exist.stat is defined
            - nginx_container_image_exist.stat.exists is defined
            - nginx_container_image_exist.stat.path is defined
            - nginx_container_image_exist.stat.path != '' 
          register: nginx_container_loaded

        - name: '{{ ansible_name_module }} | set_fact | Set loaded nginx web server container image name '
          set_fact:
            nginx_container_image: "{{ nginx_container_loaded.stdout.split(' ')[2] }}"
          when:
            - nginx_container_loaded is defined
            - nginx_container_loaded.rc is defined 
            - nginx_container_loaded.rc == 0
            - not nginx_container_loaded.failed is defined 
            - not nginx_container_loaded.failed | bool
            - nginx_container_loaded.stdout is defined
            - nginx_container_loaded.stdout != ""

    - name: '{{ ansible_name_module }} | set_fact | nginx_container_name for nginx web server'
      set_fact:
        nginx_container_name: "webserver"
      when:
        - not nginx_container_name is defined or nginx_container_name == ''

    - name: '{{ ansible_name_module }} | set_fact |  nginx_certfile for nginx web server'
      set_fact:
        nginx_certfile: "nginx.crt"
      when:
        - not nginx_certfile is defined or nginx_certfile == ''

    - name: '{{ ansible_name_module }} | set_fact | nginx_certkeyfile for nginx web server'
      set_fact:
        nginx_certkeyfile: "nginx.key"
      when:
        - not nginx_certkeyfile is defined or nginx_certkeyfile == ''

    - name: '{{ ansible_name_module }} | set_fact | nginx_http_port for nginx web server'
      set_fact:
        nginx_http_port: "8080"
      when:
        - not nginx_http_port is defined or nginx_http_port == ''

    - name: '{{ ansible_name_module }} | set_fact | nginx_host_http_port for nginx web server'
      set_fact:
        nginx_host_http_port: "8080"
      when:
        - not nginx_host_http_port is defined or nginx_host_http_port == ''

    - name: '{{ ansible_name_module }} | set_fact | nginx_https_port for nginx web server'
      set_fact:
        nginx_https_port: "8443"
      when:
        - not nginx_https_port is defined or nginx_https_port == ''

    - name: '{{ ansible_name_module }} | set_fact | nginx_host_https_port for nginx web server'
      set_fact:
        nginx_host_https_port: "8443"
      when:
        - not nginx_host_https_port is defined or nginx_host_https_port == ''

    - name: '{{ ansible_name_module }} | set_fact | nginx_container_webserver_dir for nginx web server'
      set_fact:
        nginx_container_webserver_dir: "/var/www/html/"
      when:
        - not nginx_certkeyfile is defined or nginx_certkeyfile == ''

    - name: Create a directory if it does not exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ staging_dir }}"

    - name: '{{ ansible_name_module }} | template | Render HAProxy Config'
      template:
        src: "templates/nginx.conf.j2"
        dest: "{{ staging_dir }}/nginx.conf"
        force: yes
      register: nginx_config_created

    - name: Check if the container exists from previous runs
      shell: >
        {{ podman_cli }} ps -a | grep {{ nginx_container_name }}
      register: container_stats
      failed_when:
        - container_stats is defined
        - container_stats.rc is defined
        - container_stats.rc > 1

    - name: Stop the container in case it was running from previous runs
      command: >
         {{ podman_cli }} stop {{ nginx_container_name }}
      when:
        - container_stats is defined
        - container_stats.stdout_lines is defined
        - container_stats.stdout_lines | length > 0
      register: container_nginx_stopped
    
    - name: Remove the container in case it was running from previous runs
      command: >
         {{ podman_cli }} rm -f {{ nginx_container_name }}
      when:
        - container_stats is defined
        - container_stats.stdout_lines is defined
        - container_stats.stdout_lines | length > 0
      register: container_nginx_removed

    - name: Remove the container systemd file in case it was running from previous runs
      file:
        path: /etc/systemd/system/container-{{ nginx_container_name }}.service
        state: absent
      when:
        - container_stats is defined
        - container_stats.stdout_lines is defined
        - container_stats.stdout_lines | length > 0
      register: container_nginx_removed

    # If not you get the dreaded Error: lsetxattr operation not supported error
    - name: '{{ ansible_name_module }} | podman:run | Start nginx web server container '
      command: >
        {{ podman_cli }} run -d --name {{ nginx_container_name }} \
          -p {{ nginx_host_http_port }}:{{ nginx_http_port }} -p {{ nginx_host_https_port }}:{{ nginx_https_port }} \ 
          --restart=always \
          -v {{ nginx_webserver_dir }}:{{ nginx_container_webserver_dir }}{{ append_sel }} \
          -v {{ staging_dir }}/nginx.conf:/etc/nginx/nginx.conf:z \
          -v {{ nginx_container_cert }}:/{{ nginx_certfile }} \
          -v {{ nginx_container_key }}:/{{ nginx_certkeyfile }} \
          {{ nginx_container_image }}
      vars:
        append_sel: "{{ ':z' if (is_local_vol is defined and is_local_vol | bool) else '' }}"
      register: container_nginx_started

    ### Using the --new argument to ensure all of the podman run options and arguments are included in the generated service
    - name: Generate Systemd file for container to that the nginx web server service is loaded
      command: >
        {{ podman_cli }} generate systemd --files \
        --new --restart-policy=always \
        --name {{ nginx_container_name }}
      register: container_nginx_service_created

    - name: Load Registry service file
      shell: >
         cp -Z container-{{ nginx_container_name }}.service /etc/systemd/system
      when:
        - container_nginx_service_created is defined
        - container_nginx_service_created.rc == 0
        - preserver_sectx is defined
        - preserver_sectx | bool

    - name: Load Registry service file
      copy:
        src: "container-{{ nginx_container_name }}.service"
        dest: /etc/systemd/system/container-{{ nginx_container_name }}.service
        mode: 0777
        owner: root
        group: root
        remote_src: true
        force: true
      when:
        - container_nginx_service_created is defined
        - container_nginx_service_created.rc == 0
        - not preserver_sectx is defined or not preserver_sectx | bool

    - name: Reload Systemd to that the nginx web server service is loaded
      systemd:
        daemon_reload: yes
      register: systemd_reloaded

    - name: Enable the Registry service so that the nginx web server is restarted after a reboot
      systemd:
        name: "container-{{ nginx_container_name }}.service"
        enabled: yes
      register: nginx_service_enabled
    
    - name: Enable firewalld for the nginx web server service
      firewalld:
        port: "{{ item | int }}/tcp"
        immediate: yes
        permanent: yes
        state: enabled
      when:
        - enable_firewall is defined
        - enable_firewall | bool 
      loop:
        - "{{ nginx_host_http_port }}"
        - "{{ nginx_host_https_port }}"
    
    - name: Start the Registry service so that the nginx web server is restarted after a reboot
      systemd:
        name: "container-{{ nginx_container_name }}.service"
        state: restarted
      register: nginx_service_restarted

    - name: Test that the nginx web server is up and can be connected to
      command: >
        cmd: curl -k -vv {{ nginx_host_fqdn }}:{{ nginx_host_https_port }}
      register: nginx_running

