---
- name: '{{ ansible_name_module }} | set_fact | reset api gateway ids'
  ansible.builtin.set_fact:
    aws_sts_apigateway_id: ''
    aws_sts_apigateway_root_id: ''

- name: '{{ ansible_name_module }} | Include regional api gateway creation tasks'
  ansible.builtin.include_tasks: tasks/create-regional-apigateway.yml 
  vars:
    apg_name: "{{ ccoctl_manifest_tag_name }}-regional"
    apg_description: "Regional API gateway to route https request to the private STS OIDC S3 bucket hosting the STS OIDC JWT manifest"

- name: '{{ ansible_name_module }} | Only od this is necessary'
  when:
    - configure_private_apigateway is defined
    - configure_private_apigateway | bool 
  block:
    - name: '{{ ansible_name_module }} | set_fact | reset api gateway ids'
      ansible.builtin.set_fact:
        aws_sts_apigateway_id: ''
        aws_sts_apigateway_root_id: ''
    
    - name: '{{ ansible_name_module }} | Include private api gateway creation tasks'
      ansible.builtin.include_tasks: tasks/create-private-apigateway.yml 
      vars:
        apg_name: "{{ ccoctl_manifest_tag_name }}-private"
        apg_description: "Private API gateway to route https request to the private STS OIDC S3 bucket hosting the STS OIDC JWT manifest"

