---
- name: '{{ ansible_name_module }} | Ensure the apg_resource_parent_id  is set and not an empty string'
  ansible.builtin.assert:
    that:
      - apg_resource_parent_id is defined and apg_resource_parent_id != ""
    msg: " the apg_resource_parent_id must be set to a non empty string "

- name: '{{ ansible_name_module }} | Ensure the apg_resource_path  is set and not an empty string'
  ansible.builtin.assert:
    that:
      - apg_resource_path is defined and apg_resource_path != ""
    msg: " the apg_resource_path must be set to a non empty string "

- name: '{{ ansible_name_module }} | shell:aws | Create apigateway resource '
  ansible.builtin.shell: >
    {{ aws_cli }} apigateway create-resource --rest-api-id {{ aws_sts_apigateway_id }} --parent-id {{ apg_resource_parent_id }} --path-part '{{ apg_resource_path }}' --region {{ aws_region }} --query 'id' --output text
  register: aws_sts_apigateway_resource_created_out

