---
- name: '{{ ansible_name_module }} | shell:aws | retrieve existing ocp components aws iam roles '
  ansible.builtin.shell: >
    {{ aws_cli }} iam list-roles --query 'Roles[?starts_with(RoleName, `{{ ccoctl_manifest_tag_name }}-openshift-`)].RoleName' | jq .[]
  ignore_errors: true
  register: ocp_components_aws_iam_roles_exist_out

- name: '{{ ansible_name_module }} | shell:aws | delete existing ocp component iam to recreate '
  ansible.builtin.shell: |-
    {{ aws_cli }} iam delete-role-policy --role-name {{ role_name }} --policy-name {{ role_name }}
    {{ aws_cli }} iam delete-role --role-name {{ item }}
    #ignore_errors: true
  loop: "{{ ocp_components_aws_iam_roles_exist_out.stdout_lines }}"
  vars:
    role_name: "{{ item | replace('\"', '') | trim }}"
  when:
    - ocp_components_aws_iam_roles_exist_out is defined
    - ocp_components_aws_iam_roles_exist_out.rc is defined
    - ocp_components_aws_iam_roles_exist_out.rc == 0
    - ocp_components_aws_iam_roles_exist_out.stdout_lines is defined
    - ocp_components_aws_iam_roles_exist_out.stdout_lines | length > 0
    - role_name is defined
    - role_name != ""
    - "not 'deployer' in role_name"
  register: ocp_components_aws_iam_roles_exist_out

