####### Clean Manifests Destination
- name: '{{ ansible_name_module }} | set_fact | set cluster_manifests_dir '
  ansible.builtin.set_fact:
    cluster_manifests_dir: "{{ platform_staging_dir }}/cluster/manifests"
  when:
    - not cluster_manifests_dir is defined and cluster_manifests_dir == '' 

- name: '{{ ansible_name_module }} | file:absent | Clean/Purge Old dir'
  ansible.builtin.file:
    path: "{{ cluster_manifests_dir }}"
    state: absent

- name: '{{ ansible_name_module }} | file:directory '
  ansible.builtin.file:
    path: "{{ cluster_manifests_dir }}"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0755'

####### Stage install-config
- name: '{{ ansible_name_module }} | init | file:copy | Place install-config.yaml staging dir'
  ansible.builtin.copy:
    src: "{{ cluster_install_config_file }}"
    dest: "{{ cluster_manifests_dir }}/install-config.yaml"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"

####### Generate Manifests 
- name: '{{ ansible_name_module }} | init | shell:openshift-install | create manifest'
  ansible.builtin.shell: | 
    {{ openshift_install_cli }} {{ cluster_manifests_cmd }} --dir={{ cluster_manifests_dir }}  --log-level debug
  register: manifests_created

####### Edit Manifests 
- name: '{{ ansible_name_module }} | Edit Manifest if necessary'
  when:
    - edit_manifests is defined
    - edit_manifests | bool 
    - cluster_manifests_cmd is defined
    - "'cluster manifests' in cluster_manifests_cmd"
  block:
    - name: Include manifest edit tasks
      ansible.builtin.include_tasks: tasks/edit-generated-cluster-manifests.yml 

