---
- name: 'set_fact | ansible_name_module '
  ansible.builtin.set_fact:
    ansible_name_module: "repo-overlay"
  when:
    - not ansible_name_module is defined or ansible_name_module == ''

- name: '{{ ansible_name_module }} | Ensure the cluster git_repo  is set to a valid value if ssh private key not provided'
  ansible.builtin.assert:
    that:
      - git_repo is defined and git_repo != ""
    msg: " the git_repo must be set and valid  when te ssh private key file not provided"
  when:
    - not ssh_private_key_file is defined or ssh_private_key_file == ''

- name: '{{ ansible_name_module }} | set_fact | stage_dir '
  ansible.builtin.set_fact:
    stage_dir: "/tmp/platform"
  when:
    - not stage_dir is defined or stage_dir == ''

- name: '{{ ansible_name_module }} | set_fact | fabric_root_dir '
  ansible.builtin.set_fact:
    fabric_root_dir: "aide"
  when:
    - not fabric_root_dir is defined or fabric_root_dir == ''

- name: '{{ ansible_name_module }} | set_fact | separate_git_dir '
  ansible.builtin.set_fact:
    separate_git_dir: "{{ stage_dir }}/repo"
  when:
    - not separate_git_dir is defined or separate_git_dir == ''

- name: '{{ ansible_name_module }} | set_fact | project_dir '
  ansible.builtin.set_fact:
    project_dir: "{{ stage_dir }}/project"
  when:
    - not project_dir is defined or project_dir == ''

- name: '{{ ansible_name_module }} | set_fact | git_repo_branch '
  ansible.builtin.set_fact:
    git_repo_branch: "main"
  when:
    - not git_repo_branch is defined or git_repo_branch == ''

- name: Ensure the cluster dir variable is set to a valid value
  ansible.builtin.assert:
    that:
      - cluster_dir is defined and cluster_dir != ""
    msg: " the cluster_dir must be set and valid "

- ansible.builtin.debug:
    var: ssh_private_key_file

- name: '{{ ansible_name_module }} | set_fact | project_dir '
  ansible.builtin.set_fact:
    #Leave blank if executing locally, otherwises use saved credential from AAP Controller
    ssh_private_key_file: "{{ lookup('env', 'SSH_GIT_PRIVATE_KEY') | default(omit) }}"

- name: Ensure the cluster git_repo  is set to a valid value if ssh private key not provided
  ansible.builtin.assert:
    that:
      - git_repo is defined and git_repo != ""
    msg: " the git_repo must be set and valid  when te ssh private key file not provided"
  when:
    - not ssh_private_key_file is defined or ssh_private_key_file == ''

- name: clean up tmp
  ansible.builtin.command: >
    rm -rf {{ stage_dir }}

- name: '{{ ansible_name_module }} | ansible.builtin.file | Ensure the staging dir exist '
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "{{ stage_dir }}"
    - "{{ stage_dir }}/platform"

- name: Checkout the vars variables uploads
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ project_dir }}"
    #separate_git_dir: "{{ separate_git_dir }}"
    single_branch: yes
    version: main
    update: yes
    key_file: "{{ ssh_private_key_file | default(omit) }}"
    remote: "{{ git_repo_branch }}"
    version: "{{ git_repo_branch }}"
    ssh_opts: "-o StrictHostKeyChecking=no"
  when:
    - git_repo is defined and git_repo != ''
    - cluster_dir is defined and cluster_dir != ''

- name: Copy new variables
  ansible.builtin.copy:
    src: "{{ project_dir }}/{{ cluster_dir }}/vars/"
    dest: "{{ playbook_dir }}/vars"
    mode: '0655'
    directory_mode: '0755'
  when:
    - git_repo is defined and git_repo != ''
    - cluster_dir is defined and cluster_dir != ''

- name: Remove decrypted vault file
  ansible.builtin.file:
    path: "{{ playbook_dir }}/vars/vault.yml"
    state: absent

- name: Using shell to copy the vault file into place so that it is not decrypted
  ansible.builtin.command: >
    cp {{ project_dir }}/{{ cluster_dir }}/vars/vault.yml {{ playbook_dir }}/vars/


- name: Copy cluster image manifest if applicable
  when:
    - copy_cluster_manifests is defined
    - copy_cluster_manifests | bool
  block: 
    - name: '{{ ansible_name_module }} | Check if cluster specific image manifests are defined'
      ansible.builtin.stat:
        path: "{{ project_dir }}/{{ cluster_dir }}/config/cluster-image-manifests"
        get_checksum: 'false'
      register: cluster_image_manifest_files_exist

    - name: '{{ ansible_name_module }} | set_fact | cluster_image_manifest_src_dir'
      ansible.builtin.set_fact:
        cluster_image_manifest_src_dir: "{{ cluster_image_manifest_files_exist.stat.path }}"
      when:
        - cluster_image_manifest_files_exist is defined
        - cluster_image_manifest_files_exist.stat is defined
        - cluster_image_manifest_files_exist.stat.exists is defined
        - cluster_image_manifest_files_exist.stat.exists | bool
        - cluster_image_manifest_files_exist.stat.isdir is defined
        - cluster_image_manifest_files_exist.stat.isdir | bool 

    - name: '{{ ansible_name_module }} | set_fact | cluster_image_manifest_src_dir'
      ansible.builtin.set_fact:
        cluster_image_manifest_src_dir: "{{ stage_dir }}/{{ fabric_root_dir }}/config/cluster-image-manifests"
      when:
        - not cluster_image_manifest_src_dir is defined or cluster_image_manifest_src_dir == ""

    - name: '{{ ansible_name_module }} | set_fact | cluster_image_manifest_dir '
      ansible.builtin.set_fact:
        cluster_image_manifest_dir: "cluster-image-manifests"
      when:
        - not cluster_image_manifest_dir is defined or cluster_image_manifest_dir == ""

    - name: copy cluster image manifest into place
      ansible.builtin.copy:
        src: "{{ cluster_image_manifest_src_dir }}/"
        dest: "{{ playbook_dir }}/{{ cluster_image_manifest_dir }}"
        mode: '0655'
        directory_mode: '0755'

