---
- name: '{{ ansible_name_module }} | Ensure sts_sa_key_pub_b64 is defined and nn empty'
  ansible.builtin.assert:
    that:
      - sts_sa_key_pub_b64 is defined and sts_sa_key_pub_b64 != ''
    msg: " the sts_sa_key_pub_b64 must be set to a valid b64 encode string "

- name: '{{ ansible_name_module }} | Ensure sts_sa_key_priv_b64 is defined and nn empty'
  ansible.builtin.assert:
    that:
      - sts_sa_key_priv_b64 is defined and sts_sa_key_priv_b64!= ''
    msg: " the sts_sa_key_priv_b64 must be set to a valid b64 encode string "

- name: '{{ ansible_name_module }} | ansible.builtin.file | Ensure the staging dir exist '
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "{{ ccoctl_manifests_dir }}/tls"
    - "{{ ccoctl_manifests_dir }}/tls-archive"

- name: '{{ ansible_name_module }} | Move newly create service account key artifacts to archive'
  ansible.builtin.command: > 
    mv -f {{ ccoctl_manifests_dir }}/tls/bound-service-account-signing-key.key {{ ccoctl_manifests_dir }}/serviceaccount-signer.public {{ ccoctl_manifests_dir }}/serviceaccount-signer.private {{ ccoctl_manifests_dir }}/tls-archive/
  register: new_keys_moved

- name: '{{ ansible_name_module }} | decrypt file | existing STS private key file'
  ansible.builtin.copy:
    content: "{{ sts_sa_key_pub_b64 | ansible.builtin.b64decode }}"
    dest: "{{ ccoctl_manifests_dir }}/serviceaccount-signer.public"
    force: yes
  register: existing_key_pub_staged

- name: '{{ ansible_name_module }} | decrypt file | existing STS private key file'
  ansible.builtin.copy:
    content: "{{ sts_sa_key_priv_b64 | ansible.builtin.b64decode }}"
    dest: "{{ ccoctl_manifests_dir }}/serviceaccount-signer.private"
    force: yes
  register: existing_key_priv_staged

- name: '{{ ansible_name_module }} | decrypt file | existing STS private key file'
  ansible.builtin.copy:
    content: "{{ sts_sa_key_priv_b64 | ansible.builtin.b64decode }}"
    dest: "{{ ccoctl_manifests_dir }}/tls/bound-service-account-signing-key.key"
    force: yes
  register: existing_key_spriv_staged

- name: '{{ ansible_name_module }} | decrypt oidc files '
  when:
    - stage_original_oidc_files is defined
    - stage_original_oidc_files | bool 
  block:
    - name: '{{ ansible_name_module }} | Move newly create oidc artifacts to archive'
      ansible.builtin.command: > 
        mv -f {{ ccoctl_manifests_dir }}/02-openid-configuration {{ ccoctl_manifests_dir }}/03-keys.json {{ ccoctl_manifests_dir }}/tls-archive/
      register: new_oidc_moved
    
    - name: '{{ ansible_name_module }} | decrypt file | existing oidc key file'
      ansible.builtin.copy:
        content: "{{ sts_keys_json_b64 | ansible.builtin.b64decode }}"
        dest: "{{ ccoctl_manifests_dir }}/03-keys.json"
        force: yes
      register: existing_oidc_key_staged
    
    - name: '{{ ansible_name_module }} | decrypt file | existing oidc config file'
      ansible.builtin.copy:
        content: "{{ sts_openid_configuration_b64 | ansible.builtin.b64decode }}"
        dest: "{{ ccoctl_manifests_dir }}/02-openid-configuration"
        force: yes
      register: existing_oidc_config_staged
    
