---
- name: '{{ ansible_name_module }} | set_fact | Set apigateway policy document name'
  ansible.builtin.set_fact:
    apigateway_policy_doc_file: "{{ ccoctl_manifests_dir }}/{{ apg_name }}-{{ (apigateway_policy_template | basename).split('.j2')[0] }}"

- name: '{{ ansible_name_module }} | Render aws apigateway policy manifest into place'
  ansible.builtin.template:
    src: "{{ apigateway_policy_template }}"
    dest: "{{ apigateway_policy_doc_file }}"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0655'
  register: aws_apigateway_policy_rendered

- name: '{{ ansible_name_module }} | shell:aws | apply policy document to api '
  ansible.builtin.shell: >
    {{ aws_cli }} apigateway update-rest-api --rest-api-id {{ aws_sts_apigateway_id }} --patch-operations op=replace,path=/policy,value=$(jq tostring {{ apigateway_policy_doc_file }}) --region {{ aws_region }}
  register: aws_apigateway_policy_uploaded


