---
registry_host_fqdn: '{{ vault_registry_host_fqdn }}'
local_repository: 'openshift4/operators'
registry_container_storage_dir: '/var/lib/registry'
registry_container_name: 'mirror-registry'
registry_container_image: 'quay.io/cloudctl/registry:latest'
#registry_container_image: 'docker.io/library/registry:2'
registry_container_dir: '/data/registry'
registry_admin_username: '{{ vault_registry_admin_username }}'
registry_admin_password: '{{ vault_registry_admin_password }}'
registry_container_cert: ''
registry_container_key: ''
staging_dir: '/tmp/registry'
enable_authz_on_registry: 'true'
enable_tls_on_registry: 'true'
use_custom_ca_bundle: 'true'
custom_ca_file: ''
container_context_label: ''

###### Agent installer config#####
registry_ca_file: ""
registry_pull_secret_file: ""
registry_host_fqdn: ''
local_repository: 'openshift4'
release_repository: 'openshift/release'
release_image_repository: "openshift/release-images"
ocp_release_version: "4.12.53"
enable_fips: 'true'
use_static_ips: 'true'
staging_root_dir: '/root'
deployment_staging_dir: '/root/platform-agent'
cloudctl_staging_dir: '{{ deployment_staging_dir }}/cloudctl'
platform_staging_dir: '{{ deployment_staging_dir }}/platform'
agent_install_dir: '{{ platform_staging_dir }}/install'
cluster_dir: '{{ platform_staging_dir }}'
cloud_provider: 'baremetal'
target_environment: 'baremetal'
cluster_base_domain: '{{ vault_cluster_base_domain }}'
domain_name: '{{ cluster_base_domain }}'
cluster_name: 'agent-ocp'
make_masters_schedulable: 'true'
openshift_client_binary: '/usr/local/bin/oc'
openshift_install_binary: '/usr/local/bin/openshift-install'
interface: 'eno1'
dns_servers: []
gateway: ''
netmask: '255.255.255.0'
masters: '{{ vault_masters }}'
workers: '{{ vault_workers }}'
bootstrap_instance_number: 0
master_instance_number: 3
worker_instance_number: 2
infra_instance_number: 0
api_vip_ip: ''
ingress_vip_ip: ''
overwrite_cluster_osimage: 'true'
cluster_osimage_uri: ''
cluster_osimage_sha256: ''
# SSH Keys
ssh_key_name: 'id_rsa_kubeadmin'
ssh_key_dir: '{{ platform_staging_dir }}/ssh'
sshkeys_priv_file: "{{ ssh_key_dir }}/{{ ssh_key_name }}"
sshkeys_priv_string: "{{ lookup('file', sshkeys_priv_file) }}"
sshkeys_pub_file: "{{ ssh_key_dir }}/{{ ssh_key_name }}.pub"
sshkeys_pub_string: "{{ lookup('file', sshkeys_pub_file) }}"

bootstraps: '{{ vault_bootstraps }}'
kube_api_port: 6443
machine_config_server_port: 22623
include_bootstrap: 'false'
include_masters: 'true'
include_workers: 'true'
haproxy_container_image: 'quay.io/cloudctl/haproxy:latest'
haproxy_container_cert: ''
haproxy_container_key: ''
haproxy_host_fqdn: ''
nginx_container_image: 'quay.io/cloudctl/nginx:latest'
nginx_container_cert: ''
nginx_container_key: ''
nginx_webserver_dir: ''
nginx_host_fqdn: ''
machine_cidr: []
gateway_interface: 'eno1'
icsp_file: ''
release_image_repository: 'openshift/release-images'
release_image_tag: '4.12.54-x86_64'
